### PR TITLE
Feat/how to datocms

### PR DESCRIPTION
**Pull request by ronakganatra**
This adds a how-to-datocms index linking to the academy, user-guides, and docs

### CODE REVIEW

**Review by matjack1 — APPROVED** [review]

**Comment by marcomezzavilla** [comment]
I slightly modified another component (not directly related to this feature) because particularly on this page, it was noticeable that the images had a slightly odd proportion on some resolutions.
Specifically, the vertical images appeared too large compared to the horizontal ones.

Before (mobile) ↓
before - mobile

After (mobile) ↓
after - mobile

Before (desktop) ↓
before - desktop

After (desktop) ↓
after - desktop

**Review by marcomezzavilla — APPROVED** [review]

**Comment by ronakganatra** [comment]
Nice one @marcomezzavilla thanks! I'll merge this one in the morning

**Comment by marcomezzavilla** [comment]
@ronakganatra Sure! It should be ok anywhere (:

**Comment by ronakganatra** [comment]
YOLO, merged 🫡

**Pull request merged**
